### ISSUE TITLE
Plugin loads, but unable to do anything.

### ISSUE THREAD

**Issue by nacalai** [spyratech/SuperMediaSlideShow#1]
Whenever I try clicking anything, it just blinks. I can't even press the Close-button. Running OBS 28 on W11. Would love to try experimenting with this plugin.

https://i.imgur.com/FQMRCyZ.gif

**Comment by spyratech** [comment]
Pending testing of this specific scenario.  Meanwhile other updates have occurred and this issue not seen. At this time, thought to only happen on initial script load with no scenes and or sources already configured (which are needed) so procedurally, user should set them up immediately before trying to work in settings page.  Outside of this forum, have provided nacalai with sample source files usable for creation of this authors testing demo video setup etc.  Will address this issue more aggressively if persists.

**Comment by nacalai** [comment]
I am confused. I downloaded your new build, but the same problem still occurs. I cannot click anything, not even "Close". Everything is just blinking when I try clicking something, almost as if it is refreshing all the time.

Are you saying that scenes and sources need to be pre-configured before even loading the lua script? If so, that is very backwards and should not be that way.. :)

**Comment by spyratech** [comment]
OK, sounds strange to me. I will look into this specifically.Yes, it does seem backwards to require sources be configured first. Not my intent. It should not lock up.  It should kindly do nothing until you have scenes and sources configed. Actually, I may have experienced this when I first setup the laptop and hurried to move past that as I was hunting other priorities. Please accept my apologies over this confusion. Will Track down with priority. Your effort appreciated!Will setup new clean environment tonight.KeithSent from my Phone
-------- Original message --------From: nacalai ***@***.***> Date: 12/19/22  8:37 AM  (GMT-06:00) To: spyratech/SuperMediaSlideShow ***@***.***> Cc: spyratech ***@***.***>, State change ***@***.***> Subject: Re: [spyratech/SuperMediaSlideShow] Plugin loads, but unable to do anything. (Issue #1) 
I am confused. I downloaded your new build, but the same problem still occurs. I cannot click anything, not even "Close". Everything is just blinking when I try clicking something, almost as if it is refreshing all the time.
Are you saying that scenes and sources need to be pre-configured before even loading the lua script? If so, that is very backwards and should not be that way.. :)

**Comment by Wiethoofd** [comment]
I think I experienced this issue with a misconfigured _SystemMediaCollectionCmd_ which on Windows was just a plain `dir "*.*"` for the base path, without the `/B /S` and/or `| sort` parameters, and the show just kept opening and closing the cmd prompt to get the files list. After forcefully terminating OBS and restarting it said it was missing an image source with the path containing the file info of a normal dir command without the /B /S flags, making me recheck that section of the scenes info.

**Comment by spyratech** [comment]
Wiethoofd - the problem you experienced was different.  The problem described in this thread was fixed a long time ago.  The issue you are reporting sounds to me like it is indeed a misconfigured Media Collection Command.  You need to ensure that your command returns a single one column listing of filespecs.  You can easily test your desired DIR command from within a cmd window before entering it into the SMSS Media Collection Command(s) parameters.  On Windows, the /B (bare) flag is needed to ensure the filenames/extensions are the only thing output.  Extra output such as dates and file sizes are only going to confuse the loading of the desired files.   The commands DIR and DIR star.star (asterisks) are effectively the same.  Ensure that you are using DIR with the /B flag.
